name: gomod update
description: |
  update go.mod/go.sum and make PR
inputs:
  github-token:
    description: github token
    default: ${{ github.token }}
    required: true
runs:
  using: "composite"
  steps:
  - run: go get -u
    shell: bash
  - run: go mod tidy
    shell: bash
  - name: Create PR
    uses: peter-evans/create-pull-request@v5
    with:
      token: ${{ inputs.github-token }}
      commit-message: Update Dependencies
      title: 'auto update dependencies'
      add-paths: |
        go.mod
        go.sum
