name: gomod update
description: |
  update go.mod/go.sum and make PR
inputs:
  github-token:
    description: github token
    default: ${{ github.token }}
    required: true
  go-test-args:
    description: "if set, run `go test <args>` after update; PR is skipped when the test fails"
    required: false
runs:
  using: "composite"
  steps:
  - run: go get -u
    shell: bash
  - run: go mod tidy
    shell: bash
  - name: test
    if: inputs.go-test-args != ''
    run: go test ${{ inputs.go-test-args }}
    shell: bash
  - name: Create PR
    uses: peter-evans/create-pull-request@v7
    with:
      token: ${{ inputs.github-token }}
      commit-message: Update Dependencies
      title: 'auto update dependencies'
      add-paths: |
        go.mod
        go.sum
