name: docker
description: |
  build docker image and push to registry
inputs:
  username:
    description: docker username
    required: true
    default: ${{ github.actor }}
  password:
    description: docker password
    required: true
  registry:
    description: registry hostname
    default: ghcr.io
  image-name:
    description: image name
    required: true
    default: ${{ github.repository }}
  image-version:
    description: set label
    required: false
  context:
    description: context directory
    required: true
  build-args:
    description: build args
    required: false
  platforms:
    description: image platforms
    default: linux/amd64,linux/arm64
  push:
    description: push
    default: 'false'
outputs:
  imageid:
    description: image id
    value: ${{ steps.docker-build.outputs.imageid }}
  digest:
    description: image digest
    value: ${{ steps.docker-build.outputs.digest }}
  metadata:
    description: build metadata
    value: ${{ steps.docker-build.outputs.metadata }}
  image-name:
    description: image name to pull
    value: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ github.ref_name }}

runs:
  using: "composite"
  steps:
  - uses: docker/setup-qemu-action@v2
  - uses: docker/setup-buildx-action@v3
  - name: login to container registry
    if: inputs.password != ''
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
  - name: tag version
    if: inputs.image-version != ''
    shell: bash
    run: |
      echo LABEL org.opencontainers.image.version=\"${{ inputs.image-version }}\" >> ${{ inputs.context }}/Dockerfile
  - id: docker-build
    name: build and push
    uses: docker/build-push-action@v5
    with:
      context: ${{ inputs.context }}
      build-args: ${{ inputs.build-args }}
      push: ${{ inputs.push }}
      platforms: ${{ inputs.platforms }}
      labels: |
        org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        org.opencontainers.image.authors=${{ github.repository_owner }}
        org.opencontainers.image.base.name=${{ inputs.registry }}/${{ inputs.image-name }}:${{ github.ref_name }}
      tags: |
        ${{ inputs.registry }}/${{ inputs.image-name }}:${{ github.ref_name }}
        ${{ inputs.registry }}/${{ inputs.image-name }}:latest
