name: flutter setup + analyze
description: |
  setup flutter (web-only), regenerate gitignored platform boilerplate via
  `flutter create .`, then run `flutter analyze`
inputs:
  channel:
    description: flutter channel
    default: stable
    required: false
runs:
  using: "composite"
  steps:
  - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
    with:
      channel: ${{ inputs.channel }}
      cache: true
  - name: setup project
    run: flutter create .
    shell: bash
  - name: analyze
    run: flutter analyze
    shell: bash
