name: pypi upload
description: upload file to pypi
inputs:
  username:
    description: pypi userrname
    required: true
    default: ${{ github.actor }}
  password:
    description: pypi password
    required: true
  repository_url:
    description: pypi url
    default: https://upload.pypi.org/legacy/
  file:
    description: upload file
    required: true
runs:
  using: "composite"
  steps:
  - name: deploy to pypi
    run: uv publish ${{ inputs.file }}
    shell: bash
    env:
      UV_PUBLISH_USERNAME: ${{ inputs.username }}
      UV_PUBLISH_PASSWORD: ${{ inputs.password }}
      UV_PUBLISH_URL: ${{ inputs.repository_url }}
