name: wheel
description: |
  build python package by calling `uv build --wheel`
inputs:
  output-dir:
    description: output directory
    default: dist
    required: true
outputs:
  filename:
    description: result file name
    value: ${{ steps.wheel-build.outputs.file }}
  hash:
    description: result file hash
    value: ${{ steps.wheel-build.outputs.hash }}
runs:
  using: "composite"
  steps:
  - id: wheel-build
    name: build
    run: |
      tmpd=$(mktemp -d)
      mkdir -p ${{ inputs.output-dir }}
      uv build --wheel -o $tmpd
      file=$(ls -1 $tmpd | grep '\.whl$')
      echo "file=$file" >> "$GITHUB_OUTPUT"
      echo "hash=sha256:$(sha256sum $tmpd/$file | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
      cp $tmpd/$file ${{ inputs.output-dir }}/
      rm -rf $tmpd
    shell: bash
  - name: summary
    run: |
      uv run --with pkginfo python ${{ github.action_path }}/wheel2md.py \
        ${{ inputs.output-dir }}/${{ steps.wheel-build.outputs.file }} \
        -a $GITHUB_STEP_SUMMARY
    shell: bash
  - name: wheel artifact
    uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
    with:
      name: wheel
      path: ${{ inputs.output-dir }}/${{ steps.wheel-build.outputs.file }}
