name: merge pages
description: |
  copy multiple directories for gh-pages
inputs:
  output:
    required: true
    description: output directory
    default: publish
  dirs:
    required: false
    description: directories
  pydist:
    required: false
    description: python package directory
runs:
  using: "composite"
  steps:
  - name: mkdir
    run: mkdir ${{ inputs.output }}
    shell: bash
  - name: copy files
    run: |
      for i in ${{ inputs.dirs }}; do
        cp -r $i ${{ inputs.output }}/$i
        rm -f ${{ inputs.output }}/$i/.gitignore
      done
    shell: bash
  - name: pip install pip2pi dirindex
    run: pip install pip2pi dirindex
    shell: bash
  - name: index python packages
    if: inputs.pydist != ''
    run: |
      cp -r ${{ inputs.pydist }} ${{ inputs.output }}/${{ inputs.pydist }}
      cd ${{ inputs.output }}
      dir2pi -S ${{ inputs.pydist }}
      dirindex make --template apache --hide index.html --recursive ${{ inputs.pydist }}
    shell: bash
  - name: index
    run: |
      cd ${{ inputs.output }}
      dirindex make --template apache --hide index.html .
    shell: bash
  - name: merged pages
    uses: actions/upload-pages-artifact@v3
    with:
      path: ${{ inputs.output }}
