name: rust setup + fmt/clippy
description: |
  setup rust stable toolchain, then run cargo fmt --check / cargo clippy
runs:
  using: "composite"
  steps:
  - uses: dtolnay/rust-toolchain@stable
    with:
      components: rustfmt, clippy
  - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
  - name: cargo fmt
    run: cargo fmt --check
    shell: bash
  - name: cargo clippy
    run: cargo clippy -- -D warnings
    shell: bash
