name: python + pip install
description: |
  install python and pip install
inputs:
  pipinstall:
    required: false
    description: pip install argument
runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-
  - id: setup-python
    name: setup python 3.x
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'
  - name: pip install
    if: inputs.pipinstall != ''
    run: pip install ${{ inputs.pipinstall }}
    shell: bash
outputs:
  python-version:
    description: python version string
    value: ${{ steps.setup-python.outputs.python-version }}
  python-path:
    description: python executable path
    value: ${{ steps.setup-python.outputs.python-path }}
  cache-hit:
    value: ${{ steps.setup-python.outputs.cache-hit }}
    description: cache hit or not
