name: pytest
description: |
  run pytest
inputs:
  test-readme:
    description: directory contains README.md to use pytest-readme
    required: false
runs:
  using: "composite"
  steps:
  - name: pip install pytest
    run: pip install pytest pytest-cov pytest-github-actions-annotate-failures
    shell: bash
  - name: pytest-readme
    if: inputs.test-readme != ''
    run: |
      pip install pytest-readme
      if [ -f ${{ inputs.test-readme }}/README.md ] ; then
        echo 'from pytest_readme import setup' > ${{ inputs.test-readme }}/conftest.py
        echo 'setup()' >> ${{ inputs.test-readme }}/conftest.py
      fi
    shell: bash
  - name: test
    run: PYTHONPATH=. pytest -xs
    shell: bash
  - name: summary
    run: coverage report --format markdown --omit tests >> $GITHUB_STEP_SUMMARY
    shell: bash
  - name: diff coverage
    shell: bash
    run: |
      git fetch origin ${{ github.ref_name }}
      git fetch origin ${{ github.event.repository.default_branch }}
      git checkout origin/${{ github.ref_name }}
      if git merge-base origin/${{ github.event.repository.default_branch }} HEAD ; then
        coverage xml
        pip install diff-cover
        diff-cover coverage.xml --compare-branch origin/main --markdown-report report.md
        cat report.md >> $GITHUB_STEP_SUMMARY
      else
        echo "no merge base: ${{ github.event.repository.default_branch }}"
      fi
    if: github.ref_name != github.event.repository.default_branch
  - name: coverage data
    uses: actions/upload-artifact@v4
    with:
      name: coverage
      path: |
        .coverage
        cover
        coverage.xml
