name: ruff linter
description: |
  lint by ruff
inputs:
  dirs:
    required: true
    description: directories
    default: .
runs:
  using: "composite"
  steps:
  - name: check
    run: uv run ruff check --output-format=github ${{ inputs.dirs }}
    shell: bash
  - name: format
    run: uv run ruff format --check --diff ${{ inputs.dirs }}
    shell: bash
