name: ruff linter
description: |
  lint by ruff
inputs:
  dirs:
    required: true
    description: directories
    default: .
runs:
  using: "composite"
  steps:
  - name: check
    run: uv run ruff check --output-format=github $DIRS
    shell: bash
    env:
      DIRS: ${{ inputs.dirs }}
  - name: format
    run: uv run ruff format --check --diff $DIRS
    shell: bash
    env:
      DIRS: ${{ inputs.dirs }}
