name: pinact
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: install pinact
      run: go install github.com/suzuki-shunsuke/pinact/v3/cmd/pinact@latest
      shell: bash
    - name: pin actions to SHA
      run: pinact run -u
      shell: bash
    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ github.token }}
        commit-message: "chore: pin actions to SHA"
        title: "chore: pin actions to SHA"
        branch: chore/pinact-update
        delete-branch: true
        add-paths: |
          */action.yml
          .github/workflows/*.yml
