name: check versions
on:
  workflow_dispatch: {}
jobs:
  check-version:
    name: action.yml version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: astral-sh/setup-uv@v9.0.0
      with:
        enable-cache: true
    - run: uv run --with-requirements tools/requirements.txt tools/mgmt.py check-version */action.yml
      shell: bash
